### ISSUE TITLE
Not Detecting Xcode 6.3.1

### ISSUE THREAD

**Issue by barrettj** [stepanhruda/ios-simulator-app-installer#19]
When running it outputs 'You need to have Xcode 6.3 installed and selected via xcode-select.'

I have Xcode 6.3.1 installed and selected.

**Comment by stepanhruda** [comment]
Sorry about that, fear of Xcode breaking changes and all. Released 0.1.5 that fixes it, available via `brew update && brew upgrade ios-simulator-app-installer`.
