### ISSUE TITLE
Have the simulator embedded in a mac app

### ISSUE THREAD

**Issue by hfossli** [stepanhruda/ios-simulator-app-installer#21]
We have created a framework for rendering news articles natively. The templates are written in json and we would like to create a mac app with template editor and then have the results displayed immediately in a mac app. 

Sort of like this:
![example](https://cloud.githubusercontent.com/assets/3652587/7896998/55bee6f0-06cc-11e5-9e43-8c2e43c121a4.png)

The simulator doesn't have to be embedded, but could be a separate window. 

Have you done something like this? I guess we would need to communicate via sockets to the simulator? Any thoughts?

**Comment by stepanhruda** [comment]
You'll likely need iOS Simulator running in a separate window. But it could be in the background and mirrored into your window as shown in the screenshot.

I have never done this, but it's possible to mirror the simulator screen. [Troy Gaul used this technique in Bezel](http://tgaul.net/post/107334682743/putting-watch-apps-in-context-with-bezel) – it's not open-source, but if you hit him up, he might save you a lot of trial and error.
