### ISSUE TITLE
Brew installation not working

### ISSUE THREAD

**Issue by opiator** [stepanhruda/ios-simulator-app-installer#26]
Hi there, it is failing with the following error when I do a brew install as stated in the readme:
fatal: repository 'https://github.com/stepanhruda/homebrew-ios-simulator-app-installer/' not found

**Comment by stepanhruda** [comment]
The correct command to tap is 

```
brew tap stepanhruda/ios-simulator-app-installer https://github.com/stepanhruda/ios-simulator-app-installer
```

If this doesn't work for you, can you run `brew tap` (no other arguments) and post the output here?

**Comment by stepanhruda** [comment]
Do you still have problems with this?
